### PR TITLE
Several mods

### PR DESCRIPTION
**Pull request by tzellman**
1. Updated to use ember-cli 2.10
2. Exposed several attributes for the material-icon component
3. Uses the material-design-icons bower package, and adds to the imports

### CODE REVIEW

**Comment by tzellman** [comment]
@ynnoj Just a little nudge to see if this is a change we can get merged.

Thanks! :tada:

**Comment by ynnoj** [comment]
@tzellman So sorry. I'll take a look this weekend 🙃

**Comment by tzellman** [comment]
No worries! I can relate :)

**Comment by ynnoj** [comment]
@tzellman Thanks for your contribution. I've just released [`1.1.0`](https://github.com/ynnoj/ember-material-icons/releases/tag/v1.1.0) which includes a few of the changes proposed in this PR (import assets from `npm`, bumping `ember-cli` version).

I'll close this PR, but I'd be more than happy to accept a new PR with the other changes 🙃

**Pull request closed without merging**
